package me.foesio.foKits.gui;

public enum GuiType {
    PLAYER_KITS,
    PLAYER_PREVIEW,
    ADMIN_ROOT,
    ADMIN_KIT_LIST,
    ADMIN_KIT_SETTINGS,
    ADMIN_DELETE_CONFIRM,
    ADMIN_ITEM_EDITOR,
    ADMIN_ICON_ITEM_EDITOR,
    ADMIN_CLAIMED_ITEM_EDITOR,
    ADMIN_PLAYER_GUI_LAYOUT_EDITOR,
    ADMIN_GUI_SETTINGS
}
